version=6.2.7-add-more-logging

org.gradle.caching=true
org.gradle.jvmargs=-Xmx2048m
org.gradle.parallel=true

kotlinVersion=1.9.25

kotlin.jvm.target.validation.mode=ignore
kotlin.stdlib.default.dependency=false

org.gradle.java.installations.paths=/usr/lib/jvm/jdk-17.0.16-full,/usr/lib/jvm/jdk-21.0.8-full